# docker-compose.yml for production
# This setup builds and runs the optimized production image.
#
# To update, run: docker compose build
#
services:
  app:
    build:
      context: .
      target: production # Use the 'production' stage from the Dockerfile
    platform: linux/arm64
    container_name: eleventy_prod
    volumes:
      # Persist the view count data in a named volume.
      - data:/app/_data
    restart: unless-stopped
    labels:
      diun.enable: true
      homepage.group: Tools
      homepage.name: 11ty Website
      homepage.icon: https://jesus.twk95.com/android-chrome-192x192.png
      homepage.href: ${APP_URL}
    networks:
      - proxy
volumes:
  data: null
networks:
  proxy:
    external: true
