# docker-compose.yml for production
# This setup builds and runs the optimized production image.
#
# To update, run: docker compose build
#
services:
  app:
    build:
      context: .
      target: production # Use the 'production' stage from the Dockerfile
    container_name: eleventy_prod
    ports:
      - 3000:3000
    volumes:
      # Persist the view count data in a named volume.
      - views_data:/app/_data
    restart: unless-stopped
volumes:
  views_data: null
networks: {}
