name: Build and Push Docker Image to Gitea
run-name: Build and Push Docker Image for ${{ gitea.ref_name }} by @${{ gitea.actor }}
on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build-and-push-to-gitea:
    runs-on: runner-latest

    container:
      image: docker:latest

    steps:
      - name: Install Dependencies
        run: |
          apk add --no-cache git nodejs npm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Project Dependencies
        run: npm install

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright/test | sed 's/.*@//')" >> $GITHUB_ENV

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ gitea.server_url }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.PUSH_TOKEN }}

      - name: Prepare image tags
        id: prep
        run: |
          HOST=$(echo ${{ gitea.server_url }} | sed -e 's|^https://||')
          VERSION=${{ gitea.ref_name }}
          echo "tags=${HOST}/${{ gitea.repository }}:${VERSION},${HOST}/${{ gitea.repository }}:latest" >> $GITEA_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.prep.outputs.tags }}