# .gitea/workflows/build-docker.yml
name: Build and Push Docker Image to Gitea Registry
run-name: Build and Push Docker Image for ${{ gitea.ref_name }} by @${{ gitea.actor }}

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-gitea:
    container:
      image: docker:latest
    runs-on: runner-latest
    permissions:
      packages: write

    steps:
      - name: Install Dependencies
        run: |
          apk add --no-cache git nodejs npm

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ gitea.server_url }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ gitea.server_url }}/${{ gitea.repository }}:latest, ${{ gitea.server_url }}/${{ gitea.repository }}:${{ gitea.sha }}

